server:
  port: 8081

spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/keepham?replicaSet=rs0&authSource=admin
  jpa:
    open-in-view: false
logging:
  level:
    sql: debug