spring:
  data:
    redis:
      host: localhost
      port: 46379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
      ttl: 30
