spring:
  datasource:
    url: jdbc:mysql://localhost:43306/keepham?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500  #N+1 ??? ?? ?? ??? ??? ???
        format_sql: true
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:47017/keepham
      username: root
      password: 1234

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
