spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:43306/keepham?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/keepham?replicaSet=rs0&authSource=admin
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

---
nts:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1
    key: test